version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecobalance
      POSTGRES_USER: ecobalance
      POSTGRES_PASSWORD: ecobalance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ecobalance
      RABBITMQ_DEFAULT_PASS: ecobalance

volumes:
  postgres_data: